#!/usr/bin/env bash

. $HOME/.local/share/pulse-scripts/pa-function-lib

set_app_source() {
	for i in $(get_pa_source_ids_list); do
		pw-link -d $i $1 2> /dev/null
	done
	pw-link $2 $1
}

APP=$(get_pa_app_source_index "$1")
#echo App: $APP
SOURCE=$(get_pa_source_index "$2")
#echo Source: $SOURCE

! [[ -z ${APP} ]] && ! [[ -z {SOURCE} ]] && set_app_source ${APP} ${SOURCE}
