#!/usr/bin/env bash

. $HOME/.local/share/pulse-scripts/pa-function-lib

set_app_sink() {
	pactl move-sink-input "$1" "$2"
}

APP=$(get_pa_live_app_index $1)
#echo App: $APP
SINK=$(get_pa_sink_index ${!2})
#echo Sink: $SINK

set_app_sink ${APP} ${SINK}
