#!/usr/bin/env bash

. $HOME/.local/share/pulse-scripts/pa-function-lib

INDEX=$(get_pa_app_index record "$1")

if ! [[ ${INDEX} =~ ^[0-9]+$ ]]; then
	echo "Error: App $1 not found";
	exit 1;
fi

if [[ "$2" == "+" ]]; then
	wpctl set-mute ${INDEX} 0
	wpctl set-volume -l 1.5 ${INDEX} 5%+
elif [[ "$2" == "-" ]]; then
	wpctl set-mute ${INDEX} 0
	wpctl set-volume ${INDEX} 5%-
elif [[ "$2" == "toggle" ]]; then
	wpctl set-mute ${INDEX} toggle
elif [[ $2 =~ ^[0-9]+$ ]]; then
	wpctl set-mute ${INDEX} 0
	wpctl set-volume -l 1.5 ${INDEX} $2%
else
	echo toggle/+/-/percentage e.g 50
fi
