#!/usr/bin/env bash

. $HOME/.local/share/pulse-scripts/pa-function-lib

INDEX=$(get_pa_app_source_index "$1")

if ! [[ ${INDEX} =~ ^[0-9]+$ ]]; then
	echo "Error: App $1 not found";
	exit 1;
fi

if [[ "$2" == "+" ]]; then
	wpctl set-mute ${INDEX} 0
	wpctl set-volume ${INDEX} 5%+
elif [[ "$2" == "-" ]]; then
	wpctl set-mute ${INDEX} 0
	wpctl set-volume ${INDEX} 5%-
elif [[ "$2" == "toggle" ]]; then
	wpctl set-mute ${INDEX} toggle
elif [[ $2 =~ ^[0-9]+%$ ]]; then
	wpctl set-mute ${INDEX} 0
	wpctl set-volume ${INDEX} $2
else
	echo +/-/percentage e.g 50%
fi
