#!/usr/bin/env bash

. $HOME/.local/share/pulse-scripts/pa-function-lib

set_app_sink() {
	for i in $(get_pa_connector_ids_list playback); do
		pw-link -d $1 $i 2> /dev/null
	done
	pw-link $1 $2
}

APP=$(get_pa_app_index playback "$1")
#echo App: $APP
SINK=$(get_pa_connector_index playback "$2")
#echo Sink: $SINK

! [[ -z ${APP} ]] && ! [[ -z {SINK} ]] && set_app_sink ${APP} ${SINK}
