#!/bin/bash

SELECTOR_NODE_TYPE='.type == "PipeWire:Interface:Node"'
SELECTOR_DEVICE_TYPE='.type == "PipeWire:Interface:Device"'
SELECTOR_AUDIO_DEVICE_CLASS='.info.props."media.class" == "Audio/Device"'
SELECTOR_SINK_CLASS='.info.props."media.class" == "Audio/Sink"'
SELECTOR_SOURCE_CLASS='.info.props."media.class" == "Audio/Source"'
SELECTOR_AUDIO_OUT_CLASS='.info.props."media.class" == "Stream/Output/Audio"'
SELECTOR_AUDIO_IN_CLASS='.info.props."media.class" == "Stream/Input/Audio"'

PATH_PROP_NODE_DESCRIPTION='.info.props."node.description"'
PATH_PROP_DEVICE_DESCRIPTION='.info.props."device.description"'
PATH_PROP_APP_BINARY='.info.props."application.process.binary"'
PATH_PROP_APP_NAME='.info.props."application.name"'
PATH_PROP_ID='.id'

# obtain indices
################

###
 #
 # Obtain sink index
 #
###
get_pa_sink_index() {
	LANG=LC_ALL pw-dump | \
	jq -r --arg SEARCH "$1" ".[]
		| select(${SELECTOR_NODE_TYPE} and ${SELECTOR_SINK_CLASS} and ${PATH_PROP_NODE_DESCRIPTION} == \$SEARCH)
		| ${PATH_PROP_ID}"
}

###
 #
 # Obtain source index
 #
###
get_pa_source_index() {
	LANG=LC_ALL pw-dump | \
	jq -r --arg SEARCH "$1" ".[]
		| select(${SELECTOR_NODE_TYPE} and ${SELECTOR_SOURCE_CLASS} and ${PATH_PROP_NODE_DESCRIPTION} == \$SEARCH)
		| ${PATH_PROP_ID}"
}

###
 #
 # Obtain app index
 #
###
get_pa_app_index() {
	LANG=LC_ALL pw-dump | \
	jq -r --arg SEARCH "$1" "map(
			select(
				${SELECTOR_NODE_TYPE} and ${SELECTOR_AUDIO_OUT_CLASS}
				and (${PATH_PROP_APP_BINARY} == \$SEARCH or ${PATH_PROP_APP_NAME} == \$SEARCH)
			)
		)
		| max_by(${PATH_PROP_ID})
		| ${PATH_PROP_ID}"
}	

###
 #
 # Obtain app source index
 #
###
get_pa_app_source_index() {
	LANG=LC_ALL pw-dump | \
	jq -r --arg SEARCH "$1" "map(
			select(
				${SELECTOR_NODE_TYPE} and ${SELECTOR_AUDIO_IN_CLASS}
				and (${PATH_PROP_APP_BINARY} == \$SEARCH or ${PATH_PROP_APP_NAME} == \$SEARCH)
			)
		)
		| max_by(${PATH_PROP_ID})
		| ${PATH_PROP_ID}"
}

###
 #
 # Obtain card index
 #
###
get_pa_card_index() {
	LANG=LC_ALL pw-dump | \
	jq -r --arg SEARCH "$1" ".[]
		| select(${SELECTOR_DEVICE_TYPE} and ${SELECTOR_AUDIO_DEVICE_CLASS} and ${PATH_PROP_DEVICE_DESCRIPTION} == \$SEARCH)
		| ${PATH_PROP_ID}"
}

# Obtain lists
##############

###
 #
 # Obtain sinks list
 #
###
get_pa_sinks_list() {
	LANG=LC_ALL pw-dump | \
	jq -r ".[] | select(${SELECTOR_NODE_TYPE} and ${SELECTOR_SINK_CLASS}) | ${PATH_PROP_NODE_DESCRIPTION}"
}

###
 #
 # Obtain sink ids list
 #
###
get_pa_sink_ids_list() {
	LANG=LC_ALL pw-dump | \
	jq -r ".[] | select(${SELECTOR_NODE_TYPE} and ${SELECTOR_SINK_CLASS}) | ${PATH_PROP_ID}"
}

###
 #
 # Obtain sources list
 #
###
get_pa_sources_list() {
	LANG=LC_ALL pw-dump | \
	jq -r ".[] | select(${SELECTOR_NODE_TYPE} and ${SELECTOR_SOURCE_CLASS}) | ${PATH_PROP_NODE_DESCRIPTION}"
}

###
 #
 # Obtain source ids list
 #
###
get_pa_source_ids_list() {
	LANG=LC_ALL pw-dump | \
	jq -r ".[] | select(${SELECTOR_NODE_TYPE} and ${SELECTOR_SOURCE_CLASS}) | ${PATH_PROP_ID}"
}

###
 #
 # Obtain cards list
 #
###
get_pa_cards_list() {
	LANG=LC_ALL pw-dump | \
	jq -r ".[] | select(${SELECTOR_DEVICE_TYPE} and ${SELECTOR_AUDIO_DEVICE_CLASS}) | ${PATH_PROP_DEVICE_DESCRIPTION}"
}

###
 #
 # Obtain apps list
 #
###
get_pa_app_list() {
	LANG=LC_ALL pw-dump | \
	jq -r ".[]
		| select(${SELECTOR_NODE_TYPE} and ${SELECTOR_AUDIO_OUT_CLASS})
		| if ${PATH_PROP_APP_BINARY} == null then ${PATH_PROP_APP_NAME} else ${PATH_PROP_APP_BINARY} end"
}

###
 #
 # Obtain app sources list
 #
###
get_pa_app_source_list() {
	LANG=LC_ALL pw-dump | \
	jq -r ".[]
		| select(${SELECTOR_NODE_TYPE} and ${SELECTOR_AUDIO_IN_CLASS})
		| if ${PATH_PROP_APP_BINARY} == null then ${PATH_PROP_APP_NAME} else ${PATH_PROP_APP_BINARY} end"
}

