#!/bin/bash

# obtain indices
################

###
 #
 # Obtain sink index
 #
###
get_pa_sink_index() {
	LANG=LC_ALL pw-dump | \
	jq -r --arg SINK "$1" '.[]
		| select(.type == "PipeWire:Interface:Node" and .info.props."media.class" == "Audio/Sink" and .info.props."node.description" == $SINK)
		| .info.props."object.serial"'
}

###
 #
 # Obtain source index
 #
###
get_pa_source_index() {
	LANG=LC_ALL pw-dump | \
	jq -r --arg SOURCE "$1" '.[]
		| select(.type == "PipeWire:Interface:Node" and .info.props."media.class" == "Audio/Source" and .info.props."node.description" == $SOURCE)
		| .info.props."object.serial"'
}

###
 #
 # Obtain app index
 #
###
get_pa_app_index() {
	LANG=LC_ALL pw-dump | \
	jq -r --arg APP "$1" 'map(
			select(
				.type == "PipeWire:Interface:Node" and .info.props."media.class" == "Stream/Output/Audio"
				and (.info.props."application.process.binary" == $APP or .info.props."application.name" == $APP)
			)
		)
		| max_by(.id)
		| .info.props."object.serial"'
}	

###
 #
 # Obtain app source index
 #
###
get_pa_app_source_index() {
	LANG=LC_ALL pw-dump | \
	jq -r --arg APP "$1" '.[]
		| select(
			.type == "PipeWire:Interface:Node" and .info.props."media.class" == "Stream/Input/Audio"
			and (.info.props."application.name" == $APP or .info.props."application.process.binary" == $APP)
		)
		| .info.props."object.serial"'
}

###
 #
 # Obtain card index
 #
###
get_pa_card_index() {
	LANG=LC_ALL pw-dump | \
	jq -r --arg CARD "$1" '.[]
		| select(.type == "PipeWire:Interface:Device" and .info.props."media.class" == "Audio/Device" and .info.props."device.description" == $CARD)
		| .info.props."object.serial"'
}

###
 #
 # obtain id of linked input node
 # used to be able to destroy current playback link
 #
###
get_pa_input_node_index() {
	LANG=LC_ALL pw-dump | \
	jq -r --arg OUTPUT "$1" 'map(select(.type == "PipeWire:Interface:Link" and .info."output-node-id" == ($OUTPUT|tonumber))) | max_by(.id) | .info."input-node-id"'
}

# Obtain lists
##############

###
 #
 # Obtain sinks list
 #
###
get_pa_sinks_list() {
	LANG=LC_ALL pw-dump | \
	jq -r '.[] | select(.type == "PipeWire:Interface:Node" and .info.props."media.class" == "Audio/Sink") | .info.props."node.description"'
}

###
 #
 # Obtain sources list
 #
###
get_pa_sources_list() {
	LANG=LC_ALL pw-dump | \
	jq -r '.[] | select(.type == "PipeWire:Interface:Node" and .info.props."media.class" == "Audio/Source") | .info.props."node.description"'
}

###
 #
 # Obtain sources list
 #
###
get_pa_cards_list() {
	LANG=LC_ALL pw-dump | \
	jq -r '.[] | select(.type == "PipeWire:Interface:Device" and .info.props."media.class" == "Audio/Device") | .info.props."device.description"'
}

###
 #
 # Obtain apps list
 #
###
get_pa_app_list() {
	LANG=LC_ALL pw-dump | \
	jq -r '.[]
		| select(.type == "PipeWire:Interface:Node" and .info.props."media.class" == "Stream/Output/Audio")
		| if .info.props."application.process.binary" == null then .info.props."application.name" else .info.props."application.process.binary" end'
}

###
 #
 # Obtain app sources list
 #
###
get_pa_app_source_list() {
	LANG=LC_ALL pw-dump | \
	jq -r '.[]
		| select(.type == "PipeWire:Interface:Node" and .info.props."media.class" == "Stream/Input/Audio")
		| if .info.props."application.process.binary" == null then .info.props."application.name" else .info.props."application.process.binary" end'
}

